[package]
name = "persistent-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.33", features = ["derive"] }
colored = "3.0.0"
ctrlc = "3.4.5"
dialoguer = { version = "0.11.0", features = ["fuzzy-select", "completion", "history"] }
